name: Build Image

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:${{github.event.inputs.tag}}
          build-args:
            - SCRIPT_AES256_ENCRYPTION_KEY=${{secrets.SCRIPT_AES256_ENCRYPTION_KEY}}

      - name: Run
        run: |
          docker run -d --name binaries_container godot-binaries
          docker cp binaries_container:/godot-4.2.2-stable/bin .
          docker container remove binaries_container
